-- name: InsertUser :exec
INSERT INTO REGISTRED_USERS(ID, EMAIL) VALUES (?, ?);

-- name: GetLastID :one
SELECT ID FROM REGISTRED_USERS ORDER BY ID DESC LIMIT 1;

-- name: GetEmail :one
SELECT * FROM REGISTRED_USERS WHERE EMAIL LIKE(?);