// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: queries.sql

package db

import (
	"context"
)

const getLastID = `-- name: GetLastID :one
SELECT ID FROM REGISTRED_USERS ORDER BY ID DESC LIMIT 1
`

func (q *Queries) GetLastID(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, getLastID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO REGISTRED_USERS(ID, EMAIL) VALUES (?, ?)
`

type InsertUserParams struct {
	ID    int32
	Email string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser, arg.ID, arg.Email)
	return err
}
